List to pandas dataframe

In [13]:
import pandas as pd
lst = [["hamidul",5],["mufassir",15],["sohan",30]]
print(lst)
print(type(lst))
df_list=pd.DataFrame(lst,columns=["Name","ID"],index=[1,2,3])
df_list

[['hamidul', 5], ['mufassir', 15], ['sohan', 30]]
<class 'list'>

       Name  ID
1   hamidul   5
2  mufassir  15
3     sohan  30

Tuple to pandas DataFrame

In [23]:
tup=(("Hamidul",26),("Meskat",19),("Maleka",28))
print(type(tup))
#tuple to dataframe with columns and index
df_tup=pd.DataFrame(tup,columns=["Name","Age"],index=[1,2,3])
print(type(df_tup))
df_tup

<class 'tuple'>
<class 'pandas.DataFrame'>

      Name  Age
1  Hamidul   26
2   Meskat   19
3   Maleka   28

Dictionary to pandas dataframe

In [47]:
dic={
    101:'hamidul',
    102:'asif',
    103:'sohan'
}
print(dic.items())
print(type(dic))
df_dic=pd.DataFrame(dic.items(),columns=["Id","name"])
df_dic

dict_items([(101, 'hamidul'), (102, 'asif'), (103, 'sohan')])
<class 'dict'>

    Id     name
0  101  hamidul
1  102     asif
2  103    sohan

In [42]:
dic={
    "name":["hamidul","sohan","mufassir"],
    "age":[24,24]
}
print(type(dic))
df_dic=pd.DataFrame(dic)
df_dic

<class 'dict'>

ValueError: All arrays must be of the same length

In [43]:
dic={
    "name":["hamidul","sohan","mufassir"],
    "age":[24,24,24]
}
print(type(dic))
df_dic=pd.DataFrame(dic)
df_dic

<class 'dict'>

       name  age
0   hamidul   24
1     sohan   24
2  mufassir   24

In [53]:
lst=[
    {'Name' : 'Hamidul', 'age' : 24, 'city' : 'cumilla'},
    {'Name' : 'sohan' , 'age' : 24,'city' : "Feni" },
    {'Name':"mufassir","age":24}
]
print(type(lst))
lst_df=pd.DataFrame(lst)
lst_df

<class 'list'>

       Name  age     city
0   Hamidul   24  cumilla
1     sohan   24     Feni
2  mufassir   24      NaN